### ISSUE TITLE
Feature request: Mongo date ISODate to JS timestamp

### ISSUE THREAD

**Issue by chrisMYchen** [lukasschwab/timestamp-converter#1]
Would like to be able to go from ISODate("2020-02-28T02:07:15.873Z") to JS timestamp

**Comment by lukasschwab** [comment]
Added https://lukasschwab.me/timestamp-converter/iso.html

**Comment by lukasschwab** [comment]
You're gonna have to use the unwrapped ISO date `2020-02-28T02:07:15.873Z`, though.
